version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "8005:8005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
      - D:/Javascript Projects/WifiPass1/backend/data:/app/data
  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    
    
volumes:
  mongo_data: {}
