version: '3.8'

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "8005:8005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data: {}
